# k8s/api-deployment.yaml
# Déploiement de l'API FastAPI sur Kubernetes
# Un Deployment gère le cycle de vie des pods
# replicas=2 → deux instances de l'API pour la haute disponibilité

apiVersion: apps/v1
kind: Deployment
metadata:
  name: churnguard-api
  labels:
    app: churnguard-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churnguard-api
  template:
    metadata:
      labels:
        app: churnguard-api
    spec:
      containers:
        - name: churnguard-api
          image: churnguard-api:latest
          imagePullPolicy: Never    # utilise l'image locale Docker Desktop
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"